table Dim_Date
	lineageTag: d47b7dae-e952-4bae-a83a-01f8052e925d

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 8aef3056-2b73-4379-95b0-5945f8e2a0a9
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column 'Date of Audit'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 11beee63-29d3-446e-8620-9842c675c454
		summarizeBy: none
		sourceColumn: Date of Audit
		sortByColumn: Index

		variation Variation
			isDefault
			relationship: 81903ff5-4d30-4100-b7bb-fb62103bc2d3
			defaultHierarchy: LocalDateTable_17b6b139-41ac-4390-9a70-22d6105f462c.'Date Hierarchy'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: string
		lineageTag: 832e9b87-e13e-466a-a97f-a7d8f4f76e3c
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column YEAR
		dataType: int64
		formatString: 0
		lineageTag: 91c9c456-6c04-4eee-b8d5-4dd457b4d97f
		summarizeBy: sum
		sourceColumn: YEAR

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 9288a46a-89ab-4d0a-93d4-cf60c0dec3b4
		summarizeBy: sum
		sourceColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Power BI\Survey.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"Region", "Business Unit", "Client", "Building/Location", "Total Open Reactive tasks Year-to-Date ", "Total Closed Reactive tasks Year-to-Date", "Total Open PPM tasks Year-to-Date", "Total Closed PPM tasks Year-to-Date ", "Review Five Completed PPM's from Previous Month.PPM Task Sheet Found (Document Control)", "Review Five Completed PPM's from Previous Month.PPM Task Sheet Signed (Ownership)", "Review Five Completed PPM's from Previous Month.PPM Task Sheet Filled in Correctly", "Review Five Completed PPM's from Previous Month.PPM Task Sheet has been correctly updated into CAFM", "Review Five Completed PPM's from Previous Month.Physical check the PPM was completed Correctly as per SFG20", "List the Five completed PPM's that were Reviewed", "Date of last Fire Evacuation Drill", "Date of Next Fire Evacuation Drill ", "Observe two PPM Tasks Being Carried Out.Check Method Statement and Risk Assessment is in place for PPM", "Observe two PPM Tasks Being Carried Out.Check evidence that Method statement and Risk Assessment has been briefed to Operatives", "Observe two PPM Tasks Being Carried Out.Are Operatives using the correct PPE", "Observe two PPM Tasks Being Carried Out.Was the PPM completed as per SFG20", "Observe two PPM Tasks Being Carried Out.Was the PPM task sheet filled in correctly", "Observe two PPM Tasks Being Carried Out.Operatives had correct tools and equipment", "Observe two PPM Tasks Being Carried Out.PPM task location was left clean & tidy", "Observe two PPM Tasks Being Carried Out.PPM task location was made safe prior to working (signage, lockout/tagout. etc)", "List the PPM Observed", "Log Books & Testing.Review Fire Alarm log Book ensure tests have been carried out as required", "Log Books & Testing.Review Water Treatment Log Book ensure tests have been carried out as required", "Log Books & Testing.Review Lift Log Book ensure tests have been carried out as required", "Log Books & Testing.Review BMS Log Book ensure alarms and faults have been noted and actioned", "Log Books & Testing.Fire extinguishers have had an annual maintenance inspection and service", "Log Books & Testing.Review UPS & Backup Generator Log book ensure tests have been carried out as required", "Document Control & Procedures.Emergency Escalation Plan", "Document Control & Procedures.Rain Plan", "Document Control & Procedures.Lift Entrapment Plan", "Document Control & Procedures.Water & Power Loss Procedure", "Document Control & Procedures.Fire Alarm Procedure", "Document Control & Procedures.Emergency Evacuation Procedure", "Document Control & Procedures.Mechanical and electrical line diagrams are in place", "Document Control & Procedures.Forward Maintenance Register is in place and up to date", "Document Control & Procedures.Document Control is in place", "Document Control & Procedures Comments/Observations", "House Keeping Standards.Plant Room(s) are clean, tidy and no visible watermarks/leaks", "House Keeping Standards.Plant rooms are Locked/Secured", "House Keeping Standards.Storerooms are clean, organised and tidy", "House Keeping Standards.Offices are clean and tidy", "Grooming Standards.Body Odour Acceptable", "Grooming Standards.Clean Shaven/Beard Trimmed", "Grooming Standards.Hair Neat & Tidy", "Grooming Standards.Wearing Correct Initial Uniform", "Grooming Standards.Shirt Tucked Into Trousers", "Grooming Standards.Black Belt Worn", "Grooming Standards.Black Safety Shoes Clean & Polished", "Grooming Standards.Company ID Card Visible", "Additional Comments/Observations", "Start time", "Completion time", "Email", "Name"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Columns", "YEAR-MONTH", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"YEAR-MONTH.1", "YEAR-MONTH.2"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"YEAR-MONTH.1", Int64.Type}, {"YEAR-MONTH.2", type text}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type",{"YEAR-MONTH.2"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns1", {"Date of Audit"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Duplicates",{{"Id", Int64.Type}, {"Date of Audit", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"YEAR-MONTH.1", "YEAR"}}),
				    #"Appended Query" = Table.Combine({#"Renamed Columns", Date}),
				    #"Filtered Rows" = Table.SelectRows(#"Appended Query", each true),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Index", each if [Month] = "July" then 1
				else if [Month] = "August" then 2
				else if [Month] = "September" then 3
				else if [Month] = "October" then 4
				else if [Month] = "November" then 5
				else if [Month] = "December" then 6
				else if [Month] = "January" then 7
				else if [Month] = "February" then 8
				else if [Month] = "March" then 9
				else if [Month] = "April" then 10
				else if [Month] = "May" then 11
				else if [Month] = "June" then 12
				else null),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"Index", Int64.Type}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type2",{"Id", "Index", "Date of Audit", "Month", "YEAR"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

